<div>
    @include('components.header')
    @include('components.hero-section')
    @include('components.track-section')
    @include('components.leading-framer-section')
    @include('components.pricing-plans-section')
    @include('components.faq-section')
    @include('components.footer')
</div>
